// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	crypt "go-paper/go-paper/internal/step/crypt"

	mock "github.com/stretchr/testify/mock"
)

// Encrypter is an autogenerated mock type for the Encrypter type
type Encrypter struct {
	mock.Mock
}

type Encrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *Encrypter) EXPECT() *Encrypter_Expecter {
	return &Encrypter_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function with given fields: input
func (_m *Encrypter) Encrypt(input crypt.EncrypterInput) (*crypt.EncrypterOutput, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *crypt.EncrypterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(crypt.EncrypterInput) (*crypt.EncrypterOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(crypt.EncrypterInput) *crypt.EncrypterOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypt.EncrypterOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(crypt.EncrypterInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type Encrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - input crypt.EncrypterInput
func (_e *Encrypter_Expecter) Encrypt(input interface{}) *Encrypter_Encrypt_Call {
	return &Encrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", input)}
}

func (_c *Encrypter_Encrypt_Call) Run(run func(input crypt.EncrypterInput)) *Encrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(crypt.EncrypterInput))
	})
	return _c
}

func (_c *Encrypter_Encrypt_Call) Return(_a0 *crypt.EncrypterOutput, _a1 error) *Encrypter_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Encrypter_Encrypt_Call) RunAndReturn(run func(crypt.EncrypterInput) (*crypt.EncrypterOutput, error)) *Encrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncrypter creates a new instance of Encrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encrypter {
	mock := &Encrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
