// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDGenerator is an autogenerated mock type for the IDGenerator type
type IDGenerator struct {
	mock.Mock
}

type IDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *IDGenerator) EXPECT() *IDGenerator_Expecter {
	return &IDGenerator_Expecter{mock: &_m.Mock}
}

// GenerateID provides a mock function with given fields:
func (_m *IDGenerator) GenerateID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDGenerator_GenerateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateID'
type IDGenerator_GenerateID_Call struct {
	*mock.Call
}

// GenerateID is a helper method to define mock.On call
func (_e *IDGenerator_Expecter) GenerateID() *IDGenerator_GenerateID_Call {
	return &IDGenerator_GenerateID_Call{Call: _e.mock.On("GenerateID")}
}

func (_c *IDGenerator_GenerateID_Call) Run(run func()) *IDGenerator_GenerateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDGenerator_GenerateID_Call) Return(_a0 string, _a1 error) *IDGenerator_GenerateID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDGenerator_GenerateID_Call) RunAndReturn(run func() (string, error)) *IDGenerator_GenerateID_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDGenerator creates a new instance of IDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDGenerator {
	mock := &IDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
